# Let's not use the "netlify" domain
[[redirects]]
  from = "https://aptos-tic-tac-toe.netlify.app"
  to = "https://gnazar.io"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = ".output/public"

[build.environment]
  NITRO_PRESET = "netlify"

[dev]
  command = "npm start"
  port = 3000
