/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChessAddressRouteImport } from './routes/chess.$address'
import { Route as GameCreatorNameRouteImport } from './routes/game.$creator.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChessAddressRoute = ChessAddressRouteImport.update({
  id: '/chess/$address',
  path: '/chess/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const GameCreatorNameRoute = GameCreatorNameRouteImport.update({
  id: '/game/$creator/$name',
  path: '/game/$creator/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chess/$address': typeof ChessAddressRoute
  '/game/$creator/$name': typeof GameCreatorNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chess/$address': typeof ChessAddressRoute
  '/game/$creator/$name': typeof GameCreatorNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chess/$address': typeof ChessAddressRoute
  '/game/$creator/$name': typeof GameCreatorNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chess/$address' | '/game/$creator/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chess/$address' | '/game/$creator/$name'
  id: '__root__' | '/' | '/chess/$address' | '/game/$creator/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChessAddressRoute: typeof ChessAddressRoute
  GameCreatorNameRoute: typeof GameCreatorNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chess/$address': {
      id: '/chess/$address'
      path: '/chess/$address'
      fullPath: '/chess/$address'
      preLoaderRoute: typeof ChessAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$creator/$name': {
      id: '/game/$creator/$name'
      path: '/game/$creator/$name'
      fullPath: '/game/$creator/$name'
      preLoaderRoute: typeof GameCreatorNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChessAddressRoute: ChessAddressRoute,
  GameCreatorNameRoute: GameCreatorNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
